# Request
bool stop_mode         # Stop the current mode process
bool stop_webrtc       # Stop the WebRTC bridge
bool stop_rosbridge    # Stop the ROSBridge server
---
# Response
bool success
string message
